### ISSUE TITLE
Тайтл Jackbox APP

### ISSUE THREAD

**Issue by voidlynx** [SergeyMC9730/jackbox-app#1]
1. Поменять шрифт на SF UI DIsplay Semi-Bold
2. Поставить его справа чтобы не жрало по вертикали

**Comment by SergeyMC9730** [comment]
> 
> 
>     1. Поменять шрифт на SF UI DIsplay Semi-Bold
> 
>     2. Поставить его справа чтобы не жрало по вертикали

У меня нет этого шрифта, у других челов его тоже не будет, так что надо юзать стандартные шрифты виндовса
