### ISSUE TITLE
GitHub integration with Discord

### ISSUE THREAD

**Issue by SergeyMC9730** [SergeyMC9730/jackbox-app#2]
@Calamity34 можешь настроить вебхук в настройках, а то ошибка 400 появляется?

**Comment by voidlynx** [comment]
Я сделаю это потом потому что сейчас я делаю восемь стаков бетона в майнкрафте.

Отправлено с iPhone

**Comment by voidlynx** [comment]
@SergeyMC9730 дурачок у меня нету доступа к настройкам репозитория
