### ISSUE TITLE
jackbox.tv is currently not working

### ISSUE THREAD

**Issue by voidlynx** [SergeyMC9730/jackbox-app#3]
**INVESTIGATION**: We are looking for the reason this is happening, stay calm

**Comment by SergeyMC9730** [comment]
It's very hard to fix him because I don't found any modern library for browser window on C#

**Comment by voidlynx** [comment]
А го на electron.js перепишем?

Отправлено с iPhone

**Comment by SergeyMC9730** [comment]
> 
> А го на electron.js перепишем? Отправлено с iPhone
> […](#)
> 26 июля 2020 г., в 19:03, SergeyMC9730 ***@***.***> написал(а): It's very hard to fix him because I don't found any modern library for browser window on C# — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.



> 
> А го на electron.js перепишем? Отправлено с iPhone
> […](#)
> 26 июля 2020 г., в 19:03, SergeyMC9730 ***@***.***> написал(а): It's very hard to fix him because I don't found any modern library for browser window on C# — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.

не, как мне дизайн красивый делать

**Comment by SergeyMC9730** [comment]
к тому же, elector.js весит очень много

**Comment by voidlynx** [comment]
Ну 🥞, чел, у нас и так беда с браузером и ЖС. Тут либо переписываем на JS, либо пишем/ищем библиотеку для поддержки ЖС в браузере. Других вариантов нет. Правда есть вариант написать ещё на Dart или SwiftUI.

Отправлено с iPhone
